### ISSUE TITLE
用户和用户组创建失败

### ISSUE THREAD

**Issue by zhijunlu** [threathunterX/nebula#10]
![image](https://user-images.githubusercontent.com/42799273/54595297-4d488600-4a6d-11e9-8ecb-f56d0660549a.png)
不管如何选择，在创建用户组的时候都是报失败，没有用户组，用户也创建不了~~

**Comment by threathunterX** [comment]
1.1.2版本已解决，请更新到最近版本

**Comment by test98123456** [comment]
直接拉最新版本的docker镜像吗？

**Comment by test98123456** [comment]
直接拉master的代码，新建用户分组还是失败的
