### ISSUE TITLE
风险命中数在大屏显示计数始终为0~~

### ISSUE THREAD

**Issue by zhijunlu** [threathunterX/nebula#17]
![image](https://user-images.githubusercontent.com/42799273/55301291-7229f980-546e-11e9-97c6-aa3454085b84.png)
风险命中数在大屏显示计数始终为0~~
![image](https://user-images.githubusercontent.com/42799273/55301308-84a43300-546e-11e9-9005-a54d5ae18efb.png)

**Comment by threathunterX** [comment]
这个数值是risk_score，不是风险命中数
