### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by manxuanyue** [threathunterX/nebula#20]
当我执行./build.sh -u -v 1.1.0 --apps 出现如下的报错，请帮忙看一下,谢谢
*********************************************************
环境：CentOS release 6.6  2.6.32-504.el6.x86_64
mvn -version
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-12T04:58:10+08:00)
Maven home: /opt/apache-maven-3.2.3
Java version: 1.8.0_201, vendor: Oracle Corporation
Java home: /opt/jdk1.8.0_201/jre
Default locale: en_US, platform encoding: UTF-8
Python 2.7.3
node v11.8.0
*********************************************************
[INFO] Building babel 1.9.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ babel ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ babel ---
[INFO] Installing /export/servers/nebula/src/java_lib/babel_java/pom.xml to /root/.m2/repository/com/threathunter/babel/babel/1.9.0/babel-1.9.0.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building babel-model 1.9.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.threathunter.common:threathunter.common:jar:2.6.7 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] babel .............................................. SUCCESS [  0.754 s]
[INFO] babel-model ........................................ FAILURE [  0.309 s]
[INFO] babel-util ......................................... SKIPPED
[INFO] babel-rmq .......................................... SKIPPED
[INFO] babel-redis ........................................ SKIPPED
[INFO] babel-rpc .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.367 s
[INFO] Finished at: 2019-04-11T15:45:01+08:00
[INFO] Final Memory: 6M/141M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project babel-model: Could not resolve dependencies for project com.threathunter.babel:babel-model:jar:1.9.0: Failure to find com.threathunter.common:threathunter.common:jar:2.6.7 in http://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of alimaven has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :babel-model
====== install threathunter_basictools_java v1.1.0 ======
./build.sh: line 40: cd: java_lib/threathunter_basictools_java/: No such file or directory
====== install greatdant ======
./build.sh: line 43: cd: greatdant: No such file or directory
====== install labrador ======
./build.sh: line 46: cd: labrador: No such file or directory
====== install apiserver ======
./build.sh: line 49: cd: apiserver: No such file or directory
====== offline ======
./build.sh: line 52: cd: offline: No such file or directory
====== install greyhound ======
./build.sh: line 55: cd: greyhound: No such file or directory
====== install online ======
./build.sh: line 58: cd: online: No such file or directory
./build.sh: line 60: cd: BChart: No such file or directory
====== package BChart  ======
mv: cannot stat `.git': No such file or directory
npm WARN saveError ENOENT: no such file or directory, open '/export/servers/nebula/src/java_lib/babel_java/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/export/servers/nebula/src/java_lib/babel_java/package.json'
npm WARN babel_java No description
npm WARN babel_java No repository field.
npm WARN babel_java No README data
npm WARN babel_java No license field.

up to date in 1.509s
found 0 vulnerabilities

npm ERR! path /export/servers/nebula/src/java_lib/babel_java/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/export/servers/nebula/src/java_lib/babel_java/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-11T07_45_06_865Z-debug.log
mv: cannot stat `.git.bak': No such file or directory
====== package nebula_fe  ======
cp: cannot stat `BChart/BChart-1.1.16.tgz': No such file or directory
mv: cannot stat `.git': No such file or directory
npm WARN saveError ENOENT: no such file or directory, open '/export/servers/nebula/src/java_lib/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/export/servers/nebula/src/java_lib/package.json'
npm WARN java_lib No description
npm WARN java_lib No repository field.
npm WARN java_lib No README data
npm WARN java_lib No license field.

up to date in 1.198s
found 0 vulnerabilities

npm ERR! path /export/servers/nebula/src/java_lib/BChart-1.1.16.tgz
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall stat
npm ERR! enoent ENOENT: no such file or directory, stat '/export/servers/nebula/src/java_lib/BChart-1.1.16.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-11T07_45_11_719Z-debug.log
./build.sh: line 74: cd: scripts: No such file or directory
mv: cannot stat `.git.bak': No such file or directory
====== module copying ======
copy java module
cp: cannot stat `offline/target/nebula_offline_slot-prod.tar.gz': No such file or directory
cp: cannot stat `online/nebula-onlineserver/target/nebula-onlineserver.tar.gz': No such file or directory
cp: cannot stat `apiserver/web-manager/target/java-web-release.tar.gz': No such file or directory
cp: cannot stat `labrador/application/target/labrador-release.tar.gz': No such file or directory
copy python module
cp: cannot stat `python_lib': No such file or directory
cp: cannot stat `nebula_db_writer': No such file or directory
cp: cannot stat `nebula_query_web': No such file or directory
cp: cannot stat `nebula_web': No such file or directory
copy javascript module
cp: cannot stat `nebula_fe/build/nebula_fe.tar.gz': No such file or directory
./build.sh: line 97: cd: ../nebula_apps/: No such file or directory
====== uncompress ======
uncompress java-web
tar (child): java-web-release.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
uncompress labrador
tar (child): labrador-release.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
uncompress nebula-onlineserver
tar (child): nebula-onlineserver.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
uncompress nebula_offline_slot
tar (child): nebula_offline_slot-prod.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
uncompress nebula_fe
tar (child): ./nebula_fe.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by threathunterX** [comment]
更新到最新代码，你这个代码是旧的

**Comment by manxuanyue** [comment]
> 更新到最新代码，你这个代码是旧的
两个都试了，依然报错。
git clone https://gitee.com/threathunter/nebula.git
git clone --recursive https://github.com/threathunterX/nebula.git

**Comment by threathunterX** [comment]
请根据源码编译部分文档的步骤进行操作，先更新子模块代码，再编译：
./build.sh -u -v latest --all
