### ISSUE TITLE
linux下二进制或者源码安装时nebula主进程一直是Restarting状态

### ISSUE THREAD

**Issue by allanxia** [threathunterX/nebula#5]
![image](https://user-images.githubusercontent.com/12131922/54250806-2f1beb00-4580-11e9-92f0-d100ec969bcc.png)
导致status查看状态报下面的错误：
![image](https://user-images.githubusercontent.com/12131922/54250886-6c807880-4580-11e9-94ef-86a3a3601f7a.png)

**Comment by threathunterX** [comment]
可直接  docker-compose run nebula bash 进入容器  
然后运行  supervisord -c /etc/nebula/supervisor.conf
看看报什么错

**Comment by allanxia** [comment]
处于Restarting状态没法通过 docker-compose run nebula bash 进入容器的，另外几个容器是可以进入的。

=====
我用的是云主机，内存有4G，硬盘只有50G，这个部署对硬件有严格要求么？

**Comment by threathunterX** [comment]
先docker-compose down 停掉所有镜像
再用docker-compose run nebula bash 进去
这时就是个纯净centos系统，没有启动任何业务系统的
![image](https://user-images.githubusercontent.com/31437628/54266647-c0a45080-45b2-11e9-9404-a5bc8e0f2628.png)
所以如果这样都跑不起来的话，那就见了鬼了。。。。

**Comment by allanxia** [comment]
![image](https://user-images.githubusercontent.com/12131922/54277833-dd994d80-45cb-11e9-85c5-9e1d9ac1f668.png)
我也很无奈

**Comment by allanxia** [comment]
今天更新后好了

**Comment by vincent-haoy** [comment]
你好 这里也有同样的问题，我也是不断地在restart
![acbaec938a01d6eeb1e6760e6fc0195](https://user-images.githubusercontent.com/53930677/129683532-43e5b1ca-8b29-4084-8e68-8816b18f86b7.png)


进入到 docker-compose run nebula bash 模式下报错报这个
![22647fd9cdc74551f05274ab60c32d1](https://user-images.githubusercontent.com/53930677/129683367-023673b1-39e1-48c6-ac04-4af55d7e97a6.png)

**Comment by vincent-haoy** [comment]
你好这里也有同样的问题 不停的restart downloading：
![db015af3a304842e32e6103d4ac4935](https://user-images.githubusercontent.com/53930677/129683862-c585f6e7-3f5b-45bb-9791-beea0f2ad70f.png)


当进入 docker-compose run nebula bash  模式的时候 显示的错误是：
![acbaec938a01d6eeb1e6760e6fc0195](https://user-images.githubusercontent.com/53930677/129683726-b1c20bae-06f4-4eaf-833b-d19d9fa0f520.png)
