### ISSUE TITLE
风险事件管理无数据解决办法

### ISSUE THREAD

**Issue by zhijunlu** [threathunterX/nebula#7]
风险事件管理无数据解决办法。
![image](https://user-images.githubusercontent.com/42799273/54588845-ff2c8600-4a5e-11e9-9aed-23ac35fb61cb.png)

cd nebula
#停止 
docker-compose down 
#拉取新镜像 
docker-compose pull nebula
 #启动
docker-compose up -d
./ctrl.sh start          //启动

**Comment by threathunterX** [comment]
1.1.2版本已解决，请更新到最近版本
