### ISSUE TITLE
邮件报警配置后收取不到报警邮件解决办法

### ISSUE THREAD

**Issue by zhijunlu** [threathunterX/nebula#8]
邮件报警配置后收取不到报警邮件。SMTP无法送记录。
 
![image](https://user-images.githubusercontent.com/42799273/54588964-5b8fa580-4a5f-11e9-87a6-55ec3e7f6a73.png)

收件人邮箱输入后敲回车，变成这样
![image](https://user-images.githubusercontent.com/42799273/54589035-81b54580-4a5f-11e9-93af-5edc06457a89.png)

别问我为什么会有这样的设定~~~~

**Comment by threathunterX** [comment]
测试邮件功能正常，
![image](https://user-images.githubusercontent.com/31437628/55206029-18c48f00-5210-11e9-9dc0-d641888b99b3.png)

告警邮件要在当前告警频率内有风险事件和风险数据才会发送
