### ISSUE TITLE
监控大屏无风险事件数据

### ISSUE THREAD

**Issue by zhijunlu** [threathunterX/nebula#9]
测试中 风险事件数据都有了，但是投到大屏就没有这些数据，一开始以为浏览器问题，换了各种浏览器都没用~~

![image](https://user-images.githubusercontent.com/42799273/54589209-01dbab00-4a60-11e9-829e-3e7ca0c03fe1.png)

![image](https://user-images.githubusercontent.com/42799273/54589101-b0cbb700-4a5f-11e9-8f22-671819df60a8.png)

**Comment by threathunterX** [comment]
1.1.2版本已解决，请更新到最近版本
